rvm:
 - 2.3.1
 - 2.2.5
 - ruby-head
gemfile:
  - gemfiles/Gemfile.rails-2.x
  - gemfiles/Gemfile.rails-3.x
  - Gemfile
notifications:
  recipients:
    - jarmo.p@gmail.com
matrix:
  allow_failures:
    - rvm: ruby-head

