namespace :db do
  desc "Fill database with the data from the site of febradan"
  #  +   "http://www.febraban.org.br/arquivo/bancos/sitebancos2-0.asp"
  task banks: :environment do
    Bank.create!(banco:"104", nome: "Caixa Econômica Federal")
    Bank.create!(banco:"107", nome: "Banco BBM S.A.")
    Bank.create!(banco:"119", nome: "Banco Western Union do Brasil S.A.")
    Bank.create!(banco:"125", nome: "Brasil Plural S.A. - Banco Múltiplo")
    Bank.create!(banco:"184", nome: "Banco Itaú BBA S.A.")
    Bank.create!(banco:"204", nome: "Banco Bradesco Cartões S.A.")
    Bank.create!(banco:"208", nome: "Banco BTG Pactual S.A.")
    Bank.create!(banco:"214", nome: "Banco Dibens S.A.")
    Bank.create!(banco:"217", nome: "Banco John Deere S.A.")
    Bank.create!(banco:"218", nome: "Banco Bonsucesso S.A.")
    Bank.create!(banco:"222", nome: "Banco Credit Agricole Brasil S.A.")
    Bank.create!(banco:"224", nome: "Banco Fibra S.A.")
    Bank.create!(banco:"230", nome: "Unicard Banco Múltiplo S.A.")
    Bank.create!(banco:"233", nome: "Banco Cifra S.A.")
    Bank.create!(banco:"237", nome: "Banco Bradesco S.A.")
    Bank.create!(banco:"246", nome: "Banco ABC Brasil S.A.")
    Bank.create!(banco:"248", nome: "Banco Boavista Interatlântico S.A.")
    Bank.create!(banco:"249", nome: "Banco Investcred Unibanco S.A.")
    Bank.create!(banco:"250", nome: "BCV - Banco de Crédito e Varejo S.A.")
    Bank.create!(banco:"263", nome: "Banco Cacique S.A.")
    Bank.create!(banco:"265", nome: "Banco Fator S.A.")
    Bank.create!(banco:"318", nome: "Banco BMG S.A.")
    Bank.create!(banco:"320", nome: "Banco Industrial e Comercial S.A.")
    Bank.create!(banco:"341", nome: "Banco Itaú Unibanco S.A.")
    Bank.create!(banco:"356", nome: "Banco Real S.A.")
    Bank.create!(banco:"366", nome: "Banco Société Générale Brasil S.A.")
    Bank.create!(banco:"370", nome: "Banco Mizuho do Brasil S.A.")
    Bank.create!(banco:"376", nome: "Banco J. P. Morgan S.A.")
    Bank.create!(banco:"389", nome: "Banco Mercantil do Brasil S.A.")
    Bank.create!(banco:"394", nome: "Banco Bradesco Financiamentos S.A.")
    Bank.create!(banco:"394", nome: "Banco Finasa BMC S.A.")
    Bank.create!(banco:"399", nome: "Banco HSBC Bank Brasil S.A. - Banco Múltiplo")
    Bank.create!(banco:"409", nome: "Banco UNIBANCO - União de Bancos Brasileiros S.A.")
    Bank.create!(banco:"422", nome: "Banco Safra S.A.")
    Bank.create!(banco:"453", nome: "Banco Rural S.A.")
    Bank.create!(banco:"456", nome: "Banco de Tokyo-Mitsubishi UFJ Brasil S.A.")
    Bank.create!(banco:"464", nome: "Banco Sumitomo Mitsui Brasileiro S.A.")
    Bank.create!(banco:"473", nome: "Banco Caixa Geral - Brasil S.A.")
    Bank.create!(banco:"477", nome: "Banco Citibank S.A.")
    Bank.create!(banco:"479", nome: "Banco Banco ItaúBank S.A")
    Bank.create!(banco:"487", nome: "Banco Deutsche Bank S.A. - Banco Alemão")
    Bank.create!(banco:"488", nome: "Banco JPMorgan Chase Bank")
    Bank.create!(banco:"492", nome: "Banco ING Bank N.V.")
    Bank.create!(banco:"505", nome: "Banco Credit Suisse (Brasil) S.A.")
    Bank.create!(banco:"600", nome: "Banco Luso Brasileiro S.A.")
    Bank.create!(banco:"604", nome: "Banco Industrial do Brasil S.A.")
    Bank.create!(banco:"610", nome: "Banco VR S.A.")
    Bank.create!(banco:"611", nome: "Banco Paulista S.A.")
    Bank.create!(banco:"612", nome: "Banco Guanabara S.A.")
    Bank.create!(banco:"623", nome: "Banco Panamericano S.A.")
    Bank.create!(banco:"626", nome: "Banco Ficsa S.A.")
    Bank.create!(banco:"633", nome: "Banco Rendimento S.A.")
    Bank.create!(banco:"634", nome: "Banco Triângulo S.A.")
    Bank.create!(banco:"641", nome: "Banco Alvorada S.A.")
    Bank.create!(banco:"643", nome: "Banco Pine S.A.")
    Bank.create!(banco:"652", nome: "Banco Itaú Unibanco Holding S.A.")
    Bank.create!(banco:"653", nome: "Banco Indusval S.A.")
    Bank.create!(banco:"655", nome: "Banco Votorantim S.A.")
    Bank.create!(banco:"707", nome: "Banco Daycoval S.A.")
    Bank.create!(banco:"719", nome: "Banco Banif-Banco Internacional do Funchal (Brasil)S.A.")
    Bank.create!(banco:"739", nome: "Banco BGN S.A.")
    Bank.create!(banco:"740", nome: "Banco Barclays S.A.")
    Bank.create!(banco:"745", nome: "Banco Citibank S.A.")
    Bank.create!(banco:"747", nome: "Banco Rabobank International Brasil S.A.")
    Bank.create!(banco:"748", nome: "Banco Cooperativo Sicredi S.A.")
    Bank.create!(banco:"749", nome: "Banco Simples S.A.")
    Bank.create!(banco:"751", nome: "Banco Scotiabank Brasil S.A. Banco Múltiplo")
    Bank.create!(banco:"752", nome: "Banco Banco BNP Paribas Brasil S.A.")
    Bank.create!(banco:"755", nome: "Banco Bank of America Merrill Lynch Banco Múltiplo S.A.")
    Bank.create!(banco:"756", nome: "Banco Cooperativo do Brasil S.A. - BANCOOB")
    Bank.create!(banco:"000", nome: "Banco Bankpar S.A.")
    Bank.create!(banco:"001", nome: "Banco do Brasil S.A.")
    Bank.create!(banco:"003", nome: "Banco da Amazônia S.A.")
    Bank.create!(banco:"004", nome: "Banco do Nordeste do Brasil S.A.")
    Bank.create!(banco:"012", nome: "Banco Standard de Investimentos S.A.")
    Bank.create!(banco:"021", nome: "Banco BANESTES S.A. Banco do Estado do Espírito Santo")
    Bank.create!(banco:"024", nome: "Banco de Pernambuco S.A. - BANDEPE")
    Bank.create!(banco:"025", nome: "Banco Alfa S.A.")
    Bank.create!(banco:"029", nome: "Banco Banerj S.A.")
    Bank.create!(banco:"031", nome: "Banco Beg S.A.")
    Bank.create!(banco:"033", nome: "Banco Santander (Brasil) S.A.")
    Bank.create!(banco:"036", nome: "Banco Bradesco BBI S.A.")
    Bank.create!(banco:"037", nome: "Banco do Estado do Pará S.A.")
    Bank.create!(banco:"040", nome: "Banco Cargill S.A.")
    Bank.create!(banco:"041", nome: "Banco do Estado do Rio Grande do Sul S.A.")
    Bank.create!(banco:"045", nome: "Banco Opportunity S.A.")
    Bank.create!(banco:"047", nome: "Banco do Estado de Sergipe S.A.")
    Bank.create!(banco:"062", nome: "Banco Hipercard Banco Múltiplo S.A.")
    Bank.create!(banco:"063", nome: "Banco Banco Ibi S.A. Banco Múltiplo")
    Bank.create!(banco:"064", nome: "Banco Goldman Sachs do Brasil Banco Múltiplo S.A.")
    Bank.create!(banco:"065", nome: "Banco Bracce S.A.")
    Bank.create!(banco:"069", nome: "Banco BPN Brasil Banco Múltiplo S.A.")
    Bank.create!(banco:"070", nome: "Banco BRB - Banco de Brasília S.A.")
    Bank.create!(banco:"072", nome: "Banco Rural Mais S.A.")
    Bank.create!(banco:"073", nome: "Banco BB Banco Popular do Brasil S.A.")
    Bank.create!(banco:"074", nome: "Banco J. Safra S.A.")
    Bank.create!(banco:"075", nome: "Banco ABN AMRO S.A.")
    Bank.create!(banco:"078", nome: "Banco BES Investimento do Brasil S.A.-Banco de Investimento")
    Bank.create!(banco:"079", nome: "Banco Original do Agronegócio S.A.")
    Bank.create!(banco:"095", nome: "Banco Confidence de Câmbio S.A.")
    Bank.create!(banco:"096", nome: "Banco BM&FBOVESPA de Serviços de Liquidação e Custódia S.A")
    Bank.create!(banco:"746", nome: "Banco Modal S.A.") 
  end
end

