version: '2'

services:
  postgres:
    image: 'postgres:9.6-alpine'
    restart: always
    environment:
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  transport:
    depends_on:
      - 'postgres'
    build: .
    ports:
      - "3000:3000"
    volumes:
      - '.:/usr/src/app'

volumes:
    postgres:
