version: '2'

services:
  postgres:
    image: 'postgres:9.6-alpine'
    restart: always
    environment:
      POSTGRES_PASSWORD: mypassword
    ports:
      - "54321:5432"
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "igor.batista@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "PgAdmin2019!"
    ports:
      - "5051:80"
    depends_on:
      - postgres
    # networks:
    #   - postgres-compose-network

  redis:
    image: 'redis:3.2-alpine'
    command: redis-server
    ports:
      - '63791:6379'
    volumes:
      - 'redis:/var/lib/redis/data'

  transport:
    depends_on:
      - 'postgres'
    build: .
    command: bundle exec rails s -b 0.0.0.0 #bash start.sh
    #restart: always
    # environment:
    #   - RAILS_MAIL_HOST=${RAILS_MAIL_HOST}
    #   - RAILS_MAIL_USERNAME=${RAILS_MAIL_USERNAME}
    #   - RAILS_MAIL_PASSWORD=${RAILS_MAIL_PASSWORD}
    #   - RAILS_MAIL_DOMAIN=${RAILS_MAIL_DOMAIN}
    #   - RAILS_MAIL_DESTINATION=${RAILS_MAIL_DESTINATION}
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    volumes:
      - '/home/igor/workspace/rails_app/transport:/workspace/rails_app/transport'

  # jobs:
  #   depends_on:
  #     - 'postgres'
  #     - 'redis'
  #     - 'transport'
  #   build: .
  #   command: bash start_jobs.sh
  #   volumes:
  #     - '.:/workspace/rails_app/transport'
  #   volumes_from:
  #     - box

  mailcatcher:
    image: yappabe/mailcatcher
    ports:
      - 1025:1025
      - 1080:1080

  box:
    image: busybox
    volumes:
      - /workspace/rails_app/transport/box

volumes:
    postgres:
    redis:
