version: '2'

services:
  postgres:
    image: 'postgres:9.6-alpine'
    restart: always
    environment:
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  transport:
    depends_on:
      - 'postgres'
    build: .
#    command: bash start.sh
    environment:
      - RAILS_MAIL_HOST=${RAILS_MAIL_HOST}
      - RAILS_MAIL_USERNAME=${RAILS_MAIL_USERNAME}
      - RAILS_MAIL_PASSWORD=${RAILS_MAIL_PASSWORD}
      - RAILS_MAIL_DOMAIN=${RAILS_MAIL_DOMAIN}
      - RAILS_MAIL_DESTINATION=${RAILS_MAIL_DESTINATION}
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    volumes:
      - '/home/igor/workspace/rails_app/transport:/workspace/rails_app/transport'

volumes:
    postgres:
