version: '2'

services:
  postgres:
    image: 'postgres:9.6-alpine'
    restart: always
    environment:
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  redis:
    image: 'redis:3.2-alpine'
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/var/lib/redis/data'

  transport:
    depends_on:
      - 'postgres'
    build: .
    command: bash start.sh
    environment:
      - RAILS_MAIL_HOST=${RAILS_MAIL_HOST}
      - RAILS_MAIL_USERNAME=${RAILS_MAIL_USERNAME}
      - RAILS_MAIL_PASSWORD=${RAILS_MAIL_PASSWORD}
      - RAILS_MAIL_DOMAIN=${RAILS_MAIL_DOMAIN}
      - RAILS_MAIL_DESTINATION=${RAILS_MAIL_DESTINATION}
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    volumes:
      - '/home/igor/workspace/rails_app/transport:/workspace/rails_app/transport'

  # jobs:
  #   depends_on:
  #     - 'postgres'
  #     - 'redis'
  #     - 'transport'
  #   build: .
  #   command: bash start_jobs.sh
  #   volumes:
  #     - '.:/workspace/rails_app/transport'
  #   volumes_from:
  #     - box

  mailcatcher:
    image: yappabe/mailcatcher
    ports:
      - 1025:1025
      - 1080:1080

  box:
    image: busybox
    volumes:
      - /workspace/rails_app/transport/box

volumes:
    postgres:
    redis:
